server:
  port: 9000
spring:
  rabbitmq:
    host: 192.168.65.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  #内外网隔离使用
  routes:
    order-service: /apigateway/**
  ignored-patterns: /*-service/**
  #置空忽略的头字段："Cookie", "Set-Cookie", "Authorization"
  sensitive-headers:
